pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
        maven { url 'https://developer.huawei.com/repo/' }
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        // Wear Engine SDK (HMS)
        maven { url 'https://developer.huawei.com/repo/' }
    }
}

rootProject.name = 'OpelBridge'
include ':app'
